[BUG] Refactored project related routes
b0tw/web-project pull request #33
Opened 2020-12-19 18:13 UTC by b0tw

Refactored project related routes

2020-12-19 19:57 UTC, filipdutescu requested changes

2020-12-19 19:57 UTC, filipdutescu commented on server/routers/teams.js
> +  }
really good you implemented this or I would've requested it :laughing:

2020-12-19 19:57 UTC, filipdutescu commented on server/routers/teams.js
> +  if (user.is_professor === true) {
```suggestion
  if (user && user.is_professor === true) {
```

2020-12-19 19:57 UTC, filipdutescu commented on server/routers/teams.js
> +  if (user.is_professor === true) {
```suggestion
  if (user && user.is_professor === true) {
```

2020-12-19 19:57 UTC, filipdutescu commented on server/routers/teams.js
> +      return res.status(400).send({ "message": "Something happened at deletion" })
All such responses should be:

```suggestion
      return res.status(500).json(apiError.InternalError);
```

2020-12-20 15:00 UTC, filipdutescu commented
I'll handle the remaining issues in this PR

2020-12-20 17:29 UTC, b0tw commented
Looks good

2020-12-20 17:29 UTC, filipdutescu approved these changes

2020-12-20 17:29 UTC, merged